image: node:6.6.0

stages:
  - deploy

pages:
  stage: deploy
  script:
  - npm i
  - npm run build
  - cp -r dist/* ./public
  only:
  - master
  artifacts:
    paths:
    - public

# before_script:
#  - apt-get update
#  - apt-get install -y nodejs npm
#  - npm install
#  - export NODE_ENV=production
