language: node_js

node_js:
 - 11

env:
  global:
    - CC_TEST_REPORTER_ID: cd60514dc8c96385f8e27c7f2d357e3e2a2920b2f63af6239f52ec921031eb1c

script:
 - npm run build
 - npm run report:test
 - npm run report:coverage

before_script:
 - npm i nyc -g
 - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
 - chmod +x ./cc-test-reporter
 - ./cc-test-reporter before-build

after_script:
 - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT